export const _EQUIPS = [
  {
    type: "UG",
    name: "UG1_H",
    endPointA: "H",
    volt_base: 500,
    color: "#00F",
  },
  // {
  //   type: "UG",
  //   name: "UG2_H",
  //   endPointA: "H",
  //   volt_base: 500,
  //   color: "#00F",
  // },
  {
    type: "UG",
    name: "UG1_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG2_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG3_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG4_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG5_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG6_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG7_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG8_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG9_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG10_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG11_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG12_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG13_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG14_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG15_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG16_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG17_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG18_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG19_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG20_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG21_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG22_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG23_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG24_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG25_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG26_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG27_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG28_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG29_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG30_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG31_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "C",
    volt_base: 500,
    color: "#F00",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "G",
    volt_base: 500,
    color: "#F00",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "C",
    volt_base: 500,
    color: "#F0F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "C",
    volt_base: 500,
    color: "#0F0",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "C",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#000",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
];
