export const _EQUIPS = [
  {
    type: "UG",
    name: "UG1_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG2_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "UG",
    name: "UG3_A",
    endPointA: "A",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "C",
    volt_base: 500,
    color: "#F00",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "G",
    volt_base: 500,
    color: "#F00",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "C",
    volt_base: 500,
    color: "#F0F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "C",
    volt_base: 500,
    color: "#0F0",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "C",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#000",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
  {
    type: "LT",
    endPointA: "A",
    endPointB: "B",
    volt_base: 500,
    color: "#00F",
  },
];
