export const _EQUIPS = [
  {
    type: "LT",
    endPointA: "2",
    endPointB: "6",
    r_pu: 0.0581,
    x_pu: 0.17629999999999998,
    bsh_mvar: 3.74,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "1",
    endPointB: "2",
    r_pu: 0.0192,
    x_pu: 0.0575,
    bsh_mvar: 5.28,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "1",
    endPointB: "3",
    r_pu: 0.0452,
    x_pu: 0.1852,
    bsh_mvar: 4.08,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "2",
    endPointB: "4",
    r_pu: 0.057,
    x_pu: 0.17370000000000002,
    bsh_mvar: 3.68,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "3",
    endPointB: "4",
    r_pu: 0.0132,
    x_pu: 0.0379,
    bsh_mvar: 0.84,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "2",
    endPointB: "5",
    r_pu: 0.0472,
    x_pu: 0.19829999999999998,
    bsh_mvar: 4.18,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "4",
    endPointB: "6",
    r_pu: 0.011899999999999999,
    x_pu: 0.0414,
    bsh_mvar: 0.9,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "5",
    endPointB: "7",
    r_pu: 0.046,
    x_pu: 0.11599999999999999,
    bsh_mvar: 2.04,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "6",
    endPointB: "7",
    r_pu: 0.026699999999999998,
    x_pu: 0.08199999999999999,
    bsh_mvar: 1.7,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "6",
    endPointB: "8",
    r_pu: 0.012,
    x_pu: 0.042,
    bsh_mvar: 0.9,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "6",
    endPointB: "9",
    r_pu: 0,
    x_pu: 0.20800000000000002,
    bsh_mvar: null,
    tap: 0.978,
    tap_min: 0.9,
    tap_max: 1.1,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "6",
    endPointB: "10",
    r_pu: 0,
    x_pu: 0.556,
    bsh_mvar: null,
    tap: 0.969,
    tap_min: 0.9,
    tap_max: 1.1,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "9",
    endPointB: "11",
    r_pu: 0,
    x_pu: 0.20800000000000002,
    bsh_mvar: null,
    tap: 1,
    tap_min: 1,
    tap_max: 1,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "9",
    endPointB: "10",
    r_pu: 0,
    x_pu: 0.11,
    bsh_mvar: null,
    tap: 1,
    tap_min: 1,
    tap_max: 1,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "4",
    endPointB: "12",
    r_pu: 0,
    x_pu: 0.256,
    bsh_mvar: null,
    tap: 0.932,
    tap_min: 0.9,
    tap_max: 1.1,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "12",
    endPointB: "13",
    r_pu: 0,
    x_pu: 0.14,
    bsh_mvar: null,
    tap: 1,
    tap_min: 1,
    tap_max: 1,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "12",
    endPointB: "14",
    r_pu: 0.1231,
    x_pu: 0.2559,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "12",
    endPointB: "15",
    r_pu: 0.0662,
    x_pu: 0.1304,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "12",
    endPointB: "16",
    r_pu: 0.09449999999999999,
    x_pu: 0.19870000000000002,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "14",
    endPointB: "15",
    r_pu: 0.221,
    x_pu: 0.1997,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "16",
    endPointB: "17",
    r_pu: 0.0824,
    x_pu: 0.1923,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "15",
    endPointB: "18",
    r_pu: 0.107,
    x_pu: 0.21850000000000003,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "18",
    endPointB: "19",
    r_pu: 0.0639,
    x_pu: 0.1292,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "19",
    endPointB: "20",
    r_pu: 0.034,
    x_pu: 0.068,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "10",
    endPointB: "20",
    r_pu: 0.09359999999999999,
    x_pu: 0.209,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "10",
    endPointB: "17",
    r_pu: 0.032400000000000005,
    x_pu: 0.08449999999999999,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "10",
    endPointB: "21",
    r_pu: 0.0348,
    x_pu: 0.07490000000000001,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "10",
    endPointB: "22",
    r_pu: 0.0727,
    x_pu: 0.1499,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "21",
    endPointB: "22",
    r_pu: 0.0116,
    x_pu: 0.0236,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "15",
    endPointB: "23",
    r_pu: 0.1,
    x_pu: 0.20199999999999999,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "22",
    endPointB: "24",
    r_pu: 0.115,
    x_pu: 0.179,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "23",
    endPointB: "24",
    r_pu: 0.132,
    x_pu: 0.27,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "24",
    endPointB: "25",
    r_pu: 0.1885,
    x_pu: 0.3292,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "25",
    endPointB: "26",
    r_pu: 0.2544,
    x_pu: 0.38,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "25",
    endPointB: "27",
    r_pu: 0.1093,
    x_pu: 0.2087,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "28",
    endPointB: "27",
    r_pu: 0,
    x_pu: 0.396,
    bsh_mvar: null,
    tap: 0.968,
    tap_min: 0.9,
    tap_max: 1.1,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "27",
    endPointB: "29",
    r_pu: 0.2198,
    x_pu: 0.4153,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "27",
    endPointB: "30",
    r_pu: 0.32020000000000004,
    x_pu: 0.6027,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "29",
    endPointB: "30",
    r_pu: 0.23989999999999997,
    x_pu: 0.4533,
    bsh_mvar: null,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "8",
    endPointB: "28",
    r_pu: 0.0636,
    x_pu: 0.2,
    bsh_mvar: 4.28,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
  {
    type: "LT",
    endPointA: "6",
    endPointB: "28",
    r_pu: 0.0169,
    x_pu: 0.0599,
    bsh_mvar: 1.3,
    tap: null,
    tap_min: null,
    tap_max: null,
    tap_df_deg: null,
  },
];
