export const _BARS = {
  1: {
    numero: 1,
    tipo: 2,
    id: "Barra    1",
    v_pu: 1.06,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: null,
    q_c: null,
    q_s: null,
  },
  2: {
    numero: 2,
    tipo: 1,
    id: "Barra    2",
    v_pu: 1.045,
    theta_deg: 0,
    p_g: 50,
    q_g: null,
    q_min: -40,
    q_max: 50,
    p_c: 21.7,
    q_c: 12.7,
    q_s: null,
  },
  3: {
    numero: 3,
    tipo: 0,
    id: "Barra    3",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 2.4,
    q_c: 1.2,
    q_s: null,
  },
  4: {
    numero: 4,
    tipo: 0,
    id: "Barra    4",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 7.6,
    q_c: 1.6,
    q_s: null,
  },
  5: {
    numero: 5,
    tipo: 1,
    id: "Barra    5",
    v_pu: 1.05,
    theta_deg: 0,
    p_g: 24,
    q_g: null,
    q_min: -40,
    q_max: 40,
    p_c: 94.2,
    q_c: 19,
    q_s: null,
  },
  6: {
    numero: 6,
    tipo: 0,
    id: "Barra    6",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: null,
    q_c: null,
    q_s: null,
  },
  7: {
    numero: 7,
    tipo: 0,
    id: "Barra    7",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 22.8,
    q_c: 10.9,
    q_s: null,
  },
  8: {
    numero: 8,
    tipo: 1,
    id: "Barra    8",
    v_pu: 1.01,
    theta_deg: 0,
    p_g: 22.5,
    q_g: null,
    q_min: -40,
    q_max: 40,
    p_c: 30,
    q_c: 30,
    q_s: null,
  },
  9: {
    numero: 9,
    tipo: 0,
    id: "Barra    9",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: null,
    q_c: null,
    q_s: null,
  },
  10: {
    numero: 10,
    tipo: 0,
    id: "Barra   10",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 5.8,
    q_c: 2,
    q_s: 19,
  },
  11: {
    numero: 11,
    tipo: 1,
    id: "Barra   11",
    v_pu: 1.082,
    theta_deg: 0,
    p_g: 10,
    q_g: null,
    q_min: -6,
    q_max: 24,
    p_c: null,
    q_c: null,
    q_s: null,
  },
  12: {
    numero: 12,
    tipo: 0,
    id: "Barra   12",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 11.2,
    q_c: 7.5,
    q_s: null,
  },
  13: {
    numero: 13,
    tipo: 1,
    id: "Barra   13",
    v_pu: 1.071,
    theta_deg: 0,
    p_g: 12,
    q_g: null,
    q_min: -6,
    q_max: 24,
    p_c: null,
    q_c: null,
    q_s: null,
  },
  14: {
    numero: 14,
    tipo: 0,
    id: "Barra   14",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 6.2,
    q_c: 1.6,
    q_s: null,
  },
  15: {
    numero: 15,
    tipo: 0,
    id: "Barra   15",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 8.2,
    q_c: 2.5,
    q_s: null,
  },
  16: {
    numero: 16,
    tipo: 0,
    id: "Barra   16",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 3.5,
    q_c: 1.8,
    q_s: null,
  },
  17: {
    numero: 17,
    tipo: 0,
    id: "Barra   17",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 9,
    q_c: 5.8,
    q_s: null,
  },
  18: {
    numero: 18,
    tipo: 0,
    id: "Barra   18",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 3.2,
    q_c: 0.9,
    q_s: null,
  },
  19: {
    numero: 19,
    tipo: 0,
    id: "Barra   19",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 9.5,
    q_c: 3.4,
    q_s: null,
  },
  20: {
    numero: 20,
    tipo: 0,
    id: "Barra   20",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 2.2,
    q_c: 0.7,
    q_s: null,
  },
  21: {
    numero: 21,
    tipo: 0,
    id: "Barra   21",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 17.5,
    q_c: 11.2,
    q_s: null,
  },
  22: {
    numero: 22,
    tipo: 0,
    id: "Barra   22",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: null,
    q_c: null,
    q_s: null,
  },
  23: {
    numero: 23,
    tipo: 0,
    id: "Barra   23",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 3.2,
    q_c: 1.6,
    q_s: null,
  },
  24: {
    numero: 24,
    tipo: 0,
    id: "Barra   24",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 8.7,
    q_c: 6.7,
    q_s: 4.3,
  },
  25: {
    numero: 25,
    tipo: 0,
    id: "Barra   25",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: null,
    q_c: null,
    q_s: null,
  },
  26: {
    numero: 26,
    tipo: 0,
    id: "Barra   26",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 3.5,
    q_c: 2.3,
    q_s: null,
  },
  27: {
    numero: 27,
    tipo: 0,
    id: "Barra   27",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: null,
    q_c: null,
    q_s: null,
  },
  28: {
    numero: 28,
    tipo: 0,
    id: "Barra   28",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: null,
    q_c: null,
    q_s: null,
  },
  29: {
    numero: 29,
    tipo: 0,
    id: "Barra   29",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 2.4,
    q_c: 0.9,
    q_s: null,
  },
  30: {
    numero: 30,
    tipo: 0,
    id: "Barra   30",
    v_pu: 1,
    theta_deg: 0,
    p_g: null,
    q_g: null,
    q_min: null,
    q_max: null,
    p_c: 10.6,
    q_c: 1.9,
    q_s: null,
  },
};
